# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: (.local/bin/diff-so-fancy$|\.local/bin/_tkdiff-[0-9\.]*$)
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--unsafe]
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: a30f0d816e5062a67d87c8de753cfe499672b959  # frozen: v1.5.5
  hooks:
  - id: remove-tabs
    exclude: (Makefile$|\.bat$|\.cmake$|\.eps$|\.fits$|\.opt$|.local/bin/diff-so-fancy|\.gitconfig|\.local/bin/_tkdiff-[0-9\.]*$)
