#!/usr/bin/env python3

import argparse
import csv
import logging
import subprocess
from pathlib import Path

default_header = [
    f"# This file was generated by {Path(__file__).name}.  Do not edit it directly.",
    "",
]


def confirm(prompt: str, default: bool = True) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    while True:
        answer = input(prompt + suffix).strip().lower()
        if answer in ("y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        if answer == "":
            return default
        print("Please answer y or n.")


def render_config(host: str, config: dict[str, str]) -> str:
    # Let's keep these keys at the top, in this order, and then sort the rest alphabetically
    top_keys = {key: i for i, key in enumerate(["User", "ProxyCommand"])}
    lines = []
    lines.append(f"Host {host}")
    for key, value in sorted(config.items(), key=lambda item: (top_keys.get(item[0], len(top_keys)), item[0].lower())):
        lines.append(f"    {key} {value}")
    return "\n".join(lines)


def read_config(config_file: Path) -> tuple[list[str], dict[str, dict[str, str]]]:
    header = []
    configs = {}
    if config_file.exists():
        host = None
        with config_file.open() as f:
            lines = f.read().splitlines()
        for line in lines:
            if line.startswith("Host "):
                host = line.split()[1]
                configs[host] = {}
                continue
            elif host is None:
                if line.startswith("#") or not line.strip():
                    header.append(line)
                else:
                    raise ValueError("Config file must start with a Host line")
                continue
            line = line.strip()
            if not line:
                continue
            key, value = line.split(None, 1)
            if key in configs[host]:
                raise ValueError(f"Duplicate key {key!r} for host {host!r}")
            configs[host][key] = value
    return header, configs


def get_incus_hosts() -> list[str]:
    result = subprocess.run(
        ["incus", "list", "--format=csv,header", "-c", "n"], capture_output=True, text=True, check=True
    )
    reader = csv.DictReader(result.stdout.splitlines())
    return [row["NAME"] for row in reader]


def default_cfg(host: str) -> dict[str, str]:
    return {
        "ProxyCommand": f"sh -c '(incus start {host}; incus exec {host} -- cloud-init status --wait) </dev/null >/dev/null 2>&1; exec incus exec {host} -- /usr/sbin/sshd -i'",
    }


def main(config_file: Path, force: bool):
    existing_header, existing_configs = read_config(config_file)
    # print("\n".join(existing_header))
    # print("\n\n".join(render_config(host, cfg) for host, cfg in sorted(existing_configs.items())))
    if existing_header != default_header:
        if not force:
            print("Non-default header found in existing config:")
            print("Which would you like to use?")
            print("1) Default header")
            print("\n".join(default_header))
            print("2) Existing header")
            print("\n".join(existing_header))
            while (answer := input("Enter your choice [1/2]: ")) not in ("1", "2"):
                print("Please enter 1 or 2.")
            header = {"1": default_header, "2": existing_header}[answer]
        else:
            header = default_header
    else:
        header = existing_header

    configs = {}
    incus_hosts = get_incus_hosts()

    new_hosts = set(incus_hosts) - set(existing_configs)
    removed_hosts = set(existing_configs) - set(incus_hosts)
    common_hosts = set(existing_configs) & set(incus_hosts)

    for host in sorted(removed_hosts, key=str.lower):
        print(f"Host {host!r} is no longer an incus host and will be removed from the config")
        if not force and not confirm("Do you want to remove it?"):
            configs[host] = existing_configs[host]
            continue
    for host in sorted(new_hosts, key=str.lower):
        print(f"Host {host!r} is missing from the config")
        if not force and not confirm("Do you want to add it?"):
            continue
        configs[host] = default_cfg(host)
    for host in sorted(common_hosts, key=str.lower):
        if existing_configs[host] != default_cfg(host):
            print(f"Host {host!r} has a non-default config:")
            print(render_config(host, existing_configs[host]))
            print("The default config would be:")
            print(render_config(host, default_cfg(host)))
            if force or not confirm("Do you want to update it to the default config?", default=False):
                configs[host] = existing_configs[host]
                continue
        configs[host] = default_cfg(host)

    # if there are no changes, say so and exit
    if existing_configs == configs and existing_header == header:
        print("No changes to the config")
        return

    tmp_config_file = config_file.with_suffix(".tmp")
    with tmp_config_file.open("w") as f:
        print("\n".join(header), file=f)
        print("\n\n".join(render_config(host, cfg) for host, cfg in sorted(configs.items())), file=f)

    print(f"Wrote new config to {tmp_config_file}")
    # ask if they'd like to see a diff
    if config_file.exists():
        if not force and confirm("Do you want to see a diff of the changes?"):
            subprocess.run(["diff", "-u", config_file, tmp_config_file])
    # ask if they'd like to replace the existing config with the new one
    if not force and not confirm("Do you want to replace the existing config with the new one?"):
        print("Aborting without replacing the config")
        return
    tmp_config_file.replace(config_file)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Regenerate the incus ssh config")
    parser.add_argument(
        "--log-level", "-l", default="INFO", help="Set the logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)"
    )
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Unattendly regenerate the ssh config without asking for confirmation",
    )
    parser.add_argument(
        "--config-file",
        "-c",
        default=Path.home() / ".ssh" / "config.d" / "incus.conf",
        help="Path to the ssh config file to generate",
        type=Path,
    )
    args = parser.parse_args()

    logging.basicConfig(level=getattr(logging, args.log_level.upper(), logging.INFO))

    main(args.config_file, args.force)
